language: go
go_import_path: gangleri.io/pkg/humanbytes
go:
  - 1.8.3
  - tip

script:
  - go test -v ./...

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
